[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
NODE_VERSION = "18.20.8"
NPM_CONFIG_PRODUCTION = "false" 